[project]
name = "Catan-Reinforcement-Learning"
version = "0.1.0"
description = "An implementation of the Catan game with reinforcement learning agents."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
]
