project:
  type: website
  output-dir: .

website:
  title: "Playing Catan with Monte Carlo Tree Search"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



